"""/dream's generative payload — DRM-6: schema/gist + hypotheses (Tier B, quarantined).

The edge backbone (DRM-1..5) CONNECTS existing memories; this module is the tier that
creates net-new ones: **schema/gist** parents abstracted over a co-firing cluster (the
token-reduction + generalization-query win) and **hypothesis** memories recombining
distant pairs (A+B ⇒ likely-C). Both ASSERT claims, which is where FM1/FM2 and the
dream-cites-a-dream tower bite hardest — so the whole tier is QUARANTINED, SELF-DECAYING,
and OPT-IN:

  - **Behind a flag** (``HIPPO_DREAM_GENERATIVE``; default OFF — DREAM-KILL-1: never
    auto-applied as verified). ``dream --generate`` reports proposals anywhere; staging
    them needs the flag or the explicit ``--stage``.
  - **Created ONLY at ``confidence: draft``** — the staging path hard-codes the tier;
    a tampered proposal cannot land verified. Drafts enter recall DOWN-WEIGHTED (the
    ×0.5 quarantine weight recall applies since DRM-6 wired GOV-7's tier into ranking),
    are EXCLUDED from abstention-sensitive answering (a draft-only result set collapses
    back to the abstention shape), and are never floor material (``type: project``).
  - **Self-decaying**: a draft unconfirmed past ``DREAM_DRAFT_HORIZON`` distinct sessions
    auto-closes its validity window (``staleness.set_invalid_after`` — /dream's own
    artifact, reversible, ranking-only effect: the reversibility-gradient extension of
    DRM-4's "own un-aged edges may auto-retract") and AUTO-PROPOSES ARCHIVE; the archive
    itself (``--archive-draft``) stays a per-item act (inv4). A generation tier without
    this decay path must not ship — the sweep runs inside every apply pass whenever
    generated rows exist, independent of the flag staying on.
  - **Graduation is EXTERNAL-EVIDENCE-ONLY**: draft→verified happens exactly when the
    recorded outcome ledger (``outcome.injection_hits``, the KPI-2 join — the memory was
    injected AND one of its cited files was touched that session) carries evidence for
    the draft. Never a second human glance, never the pass grading its own output — the
    ONLY confidence write in this module is the evidence-gated branch in the sweep
    (asserted by test: no self-graduation path exists).
  - **The firewall extends to generative output** (inv-DRM-firewall): a draft is never
    replay SOURCE (seed or endpoint — ``dream.discover`` excludes the tier), a
    graduated-but-young generated memory stays excluded until it AGES IN
    (``dream.unaged_generated_stems``, same ``DREAM_AGE_SESSIONS`` window as edges), and
    the firewalled graph view drops quarantined NODES entirely so a draft parent's own
    wikilinks can never manufacture the next pass's bridge distances.
  - **Reversible-autonomy discipline carried over from DRM-2**: hard secret BLOCK on
    every generated byte (the ratified dream-write-path deviation from secrets.py's
    WARN-never-BLOCK), per-pass cap (``DREAM_MAX_GENERATE_PER_PASS`` ≤ 5), complete
    provenance in the committed ``dream-ledger.jsonl`` + an on-disk ``edge=`` stamp
    (doctor-reconciled), byte-exact undo (``--undo <id>`` deletes the staged file;
    refuse-on-drift protects a hand-edited or graduated draft), NEVER an autonomous
    commit, and a previously undone/archived/expired cluster is never auto re-staged
    (the ping-pong guard, keyed on the children set).

Measurement (the honesty surface):
  - **Prospective recall** — at first staging the current ``telemetry.abstention_backlog``
    is FROZEN under the derived dream dir; ``dream --prospective`` re-runs each frozen
    cluster's query and counts abstain→hit flips, attributing flips that surface a
    generated memory. The metric a schema tier must move.
  - **Graduation-rate alarm** — the sweep reports staged/graduated/expired/archived/
    undone counts and flags LOW graduation among decided drafts loudly: a generator
    whose claims the world never confirms is hallucinating, and the report says so.

Landing zone (re-verified against the live tree): generated drafts are staged INTO THE
CORPUS via ``new_memory.write_memory`` — the one canonical create primitive (refuses
overwrite, folds SEC-6 trust, refreshes the index) — because every quarantine mechanic
above (down-weight, abstention guard, decay, outcome join, prospective flips) operates on
RECALLABLE memories. The gitignored ``.claude/.memory-pending/`` queue the roadmap
snapshot named is the home for *unreviewed session text awaiting a human* (capture seeds,
SIG-6 fixture drafts); parking claims there would leave the tier inert — no recall
influence, no evidence, no decay, and the prospective-recall metric unsatisfiable. The
corpus + ``confidence: draft`` IS the quarantine.
"""

from __future__ import annotations

import json
import os
import re
from collections import Counter
from datetime import datetime, timezone
from typing import Dict, List, Optional, Set, Tuple

from .dream import (
    _GENERATED_KINDS,
    apply_ledger_path,
    cofire_theta,
    dream_dir,
    generated_rows,
)
from .links import normalize_slug
from .provenance import parse_frontmatter
from .soak import soak_status
from .telemetry import current_session_id, default_telemetry_dir

# --------------------------------------------------------------------------- #
# Tunables (env-overridable; defaults chosen for the empty-norm)
# --------------------------------------------------------------------------- #

# Per-pass cap on STAGED generated memories (schemas + hypotheses combined). Generation
# is rarer than edges by design — inv-DRM-empty-norm applies to this tier too; the hard
# max is not overridable (DREAM-KILL-4's no-bulk spirit).
_DEFAULT_MAX_GENERATE = 2
_HARD_MAX_GENERATE = 5

# Distinct sessions a draft may live unconfirmed before it expires (auto-invalidated +
# archive-proposed). 2× the edge aging window by default: a draft needs time to be
# injected and earn an outcome before the tier declares it unconfirmed.
_DEFAULT_DRAFT_HORIZON = 10

# Minimum co-firing cluster size for a schema parent — a pair is not a pattern; three
# mutually co-firing memories are the smallest cluster where one abstraction pays for
# its own injection tokens.
_DEFAULT_SCHEMA_MIN_CLUSTER = 3

# Maximum cluster size that still reads as ONE pattern. CALIBRATED 2026-07-12 on the
# live corpus: at θ=0.90 the dense release-history family fused into a single 19-member
# mutual component — a "schema" over 19 children is a haystack, not a gist, and its
# parent would be BORN over DRM-4's hub bar (DREAM_MAX_OUT_DEGREE default 8): staged
# pre-flagged as a parasite. The default deliberately equals that hub cap — the two
# counterweights agree by construction. An oversized component is reported as a
# θ-under-discriminates signal (raise DREAM_COFIRE_THETA), never staged.
_DEFAULT_SCHEMA_MAX_CLUSTER = 8

# Shared-vocabulary extraction: a token must appear in at least this many children's
# descriptions to count as cluster vocabulary, and must be at least this long.
_MIN_TOKEN_LEN = 4
_MAX_SHARED_TOKENS = 8
_MAX_NAME_TOKENS = 3
_MAX_CITED_PATHS = 10
_MAX_QUERIES_SHOWN = 2
_DESC_CHILD_LIST_LIMIT = 4

# The alarm bar: once this many generated drafts have been DECIDED (graduated, expired,
# archived, or undone), a graduation rate below the floor is called out loudly.
_ALARM_MIN_DECIDED = 3
_ALARM_GRADUATION_FLOOR = 1 / 3

_FROZEN_BACKLOG_NAME = "abstention-frozen.json"


def _env_int(name: str, default: int) -> int:
    try:
        raw = os.environ.get(name, "").strip()
        return int(raw) if raw else default
    except (TypeError, ValueError):
        return default


def generative_enabled() -> bool:
    """``HIPPO_DREAM_GENERATIVE`` — the DRM-6 flag. DEFAULT OFF (P3 ships behind a flag;
    DREAM-KILL-1). Only an explicit truthy value enables; junk stays off."""
    return os.environ.get("HIPPO_DREAM_GENERATIVE", "").strip() in ("1", "true", "True")


def max_generate_per_pass() -> int:
    """``DREAM_MAX_GENERATE_PER_PASS`` clamped to [0, 5] — the hard max is not overridable."""
    return max(0, min(_env_int("DREAM_MAX_GENERATE_PER_PASS", _DEFAULT_MAX_GENERATE), _HARD_MAX_GENERATE))


def draft_horizon() -> int:
    """``DREAM_DRAFT_HORIZON`` (≥1) — distinct sessions before an unconfirmed draft expires."""
    return max(1, _env_int("DREAM_DRAFT_HORIZON", _DEFAULT_DRAFT_HORIZON))


def schema_min_cluster() -> int:
    """``DREAM_SCHEMA_MIN_CLUSTER`` (≥3) — smallest co-firing cluster that earns a parent."""
    return max(3, _env_int("DREAM_SCHEMA_MIN_CLUSTER", _DEFAULT_SCHEMA_MIN_CLUSTER))


def schema_max_cluster() -> int:
    """``DREAM_SCHEMA_MAX_CLUSTER`` — largest cluster that still reads as one pattern
    (never below the min bar; see the calibration note on the default)."""
    return max(schema_min_cluster(), _env_int("DREAM_SCHEMA_MAX_CLUSTER", _DEFAULT_SCHEMA_MAX_CLUSTER))


# --------------------------------------------------------------------------- #
# Clustering DRM-1's co-firing sets
# --------------------------------------------------------------------------- #
def cluster_cofire(pairs: List[dict], *, theta: Optional[float] = None) -> dict:
    """Cluster the discovery pass's co-fired pairs into schema clusters + hypothesis pairs.

    Input rows are ``discover()``'s ``pairs`` (``{a, b, cofire, mutual, distance, query}``,
    already firewall-clean: floor / draft / un-aged generated stems never reach the pair
    set). The generation bar is deliberately the CALIBRATED apply bar, not a new dial:
    MUTUAL co-fire AND ``cofire ≥ θ`` — the separator the live distribution exposed.

      - **schema clusters**: connected components over the strong-mutual pairs with
        ``schema_min_cluster() ≤ size ≤ schema_max_cluster()`` (a pair is not a pattern;
        a mega-component is θ under-discriminating, not a pattern either — it lands in
        ``oversized`` for the report, never in ``clusters``).
      - **hypothesis pairs**: strong-mutual pairs whose graph DISTANCE is unknown
        (disconnected or beyond the BFS cutoff — "distant memories" literally) and whose
        endpoints sit in no component of schema size or above (the schema claims first,
        and an oversized component's members are CONNECTED, not distant).

    Pure; deterministic (components sorted by size desc then name; pairs by strength).
    """
    th = cofire_theta() if theta is None else theta
    strong = [
        p
        for p in pairs or []
        if p.get("mutual") and (p.get("cofire") or 0.0) >= th
        and isinstance(p.get("a"), str) and isinstance(p.get("b"), str)
    ]

    parent: Dict[str, str] = {}

    def _find(x: str) -> str:
        while parent.get(x, x) != x:
            parent[x] = parent.get(parent[x], parent[x])
            x = parent[x]
        return x

    def _union(x: str, y: str) -> None:
        parent.setdefault(x, x)
        parent.setdefault(y, y)
        rx, ry = _find(x), _find(y)
        if rx != ry:
            parent[max(rx, ry)] = min(rx, ry)

    for p in strong:
        _union(p["a"], p["b"])

    components: Dict[str, Set[str]] = {}
    for stem in parent:
        components.setdefault(_find(stem), set()).add(stem)
    lo, hi = schema_min_cluster(), schema_max_cluster()
    sized = sorted(
        (sorted(members) for members in components.values() if len(members) >= lo),
        key=lambda c: (-len(c), c[0]),
    )
    clusters = [c for c in sized if len(c) <= hi]
    oversized = [c for c in sized if len(c) > hi]
    clustered = {s for c in sized for s in c}

    hypothesis_pairs = sorted(
        (
            p
            for p in strong
            if p.get("distance") is None
            and p["a"] not in clustered
            and p["b"] not in clustered
        ),
        key=lambda p: (-(p.get("cofire") or 0.0), p["a"], p["b"]),
    )
    return {"clusters": clusters, "oversized": oversized, "hypothesis_pairs": hypothesis_pairs}


# --------------------------------------------------------------------------- #
# Proposal synthesis (mechanical, deterministic — the agent may edit before staging,
# but the templated form is complete and honest on its own)
# --------------------------------------------------------------------------- #
_TOKEN_RE = re.compile(r"[a-z0-9][a-z0-9_-]{%d,}" % (_MIN_TOKEN_LEN - 1))


def _description_of(texts: Dict[str, str], stem: str) -> str:
    try:
        fm = parse_frontmatter(texts.get(stem, "")) or {}
        d = fm.get("description")
        return d.strip() if isinstance(d, str) else ""
    except Exception:
        return ""


def _cited_paths_of(texts: Dict[str, str], stem: str) -> List[str]:
    try:
        fm = parse_frontmatter(texts.get(stem, "")) or {}
        meta = fm.get("metadata") if isinstance(fm.get("metadata"), dict) else {}
        val = fm.get("cited_paths")
        if val is None:
            val = (meta or {}).get("cited_paths")
        if isinstance(val, str):
            val = [val]
        return [p.strip() for p in val if isinstance(p, str) and p.strip()] if isinstance(val, list) else []
    except Exception:
        return []


def _shared_tokens(descriptions: List[str], min_docs: int = 2) -> List[str]:
    """Tokens appearing in ≥ ``min_docs`` of the descriptions — the cluster's shared
    vocabulary, most-common first then alphabetical. This is what makes the parent HIT
    for generalization queries: its description carries the vocabulary the children share."""
    per_doc = [set(_TOKEN_RE.findall((d or "").lower())) for d in descriptions]
    counts = Counter(t for doc in per_doc for t in doc)
    shared = [(c, t) for t, c in counts.items() if c >= min(min_docs, len(per_doc))]
    shared.sort(key=lambda ct: (-ct[0], ct[1]))
    return [t for _c, t in shared[:_MAX_SHARED_TOKENS]]


def _proposal_name(prefix: str, members: List[str], shared: List[str], existing: Set[str]) -> str:
    """Deterministic ``<prefix>-tok1-tok2-tok3`` name from shared vocabulary (slug-token
    fallback), suffixed ``-2``, ``-3``… on collision with an existing stem."""
    tokens: List[str] = []
    pool = shared or []
    if not pool:
        slug_counts = Counter(t for m in members for t in normalize_slug(m).split("-") if len(t) >= 3)
        pool = [t for t, _c in sorted(slug_counts.items(), key=lambda tc: (-tc[1], tc[0]))]
    for t in pool:
        t = normalize_slug(t)
        if t and t not in tokens:
            tokens.append(t)
        if len(tokens) >= _MAX_NAME_TOKENS:
            break
    base = "-".join([prefix] + (tokens or ["cluster"]))
    name = base
    n = 2
    lowered = {normalize_slug(s) for s in existing}
    while normalize_slug(name) in lowered:
        name = f"{base}-{n}"
        n += 1
    return name


def _truncate(s: str, n: int) -> str:
    s = (s or "").replace("\n", " ").strip()
    return s if len(s) <= n else s[: n - 1].rstrip() + "…"


_QUARANTINE_BANNER = (
    "> **Dream-drafted — quarantined.** Generated by /dream's generative tier at\n"
    "> `confidence: draft`: enters recall down-weighted, never answers alone, and\n"
    "> auto-proposes archive at the draft horizon unless a RECORDED OUTCOME event\n"
    "> (injected + a cited file touched that session) graduates it to verified.\n"
    "> Treat as a hypothesis about structure, not a fact.\n"
)


def propose_generative(
    result: dict, texts: Dict[str, str], *, theta: Optional[float] = None
) -> dict:
    """Turn one discovery result into staged-ready proposals. Pure over its inputs.

    Returns ``{"schemas": [...], "hypotheses": [...]}``; each proposal carries
    ``{kind, name, description, body, children, cofire, queries, cited_paths}``.
    ``confidence`` is deliberately NOT a proposal field — staging hard-codes draft.
    """
    pairs = result.get("pairs") or []
    grouped = cluster_cofire(pairs, theta=theta)
    existing = set(texts)
    by_pair = {frozenset((p["a"], p["b"])): p for p in pairs}
    th = cofire_theta() if theta is None else theta

    # Oversized components ride along for the REPORT only (a θ-under-discriminates
    # signal, never a proposal — see schema_max_cluster's calibration note).
    proposals: dict = {"schemas": [], "hypotheses": [], "oversized": grouped["oversized"]}
    claimed_names: Set[str] = set(existing)

    for members in grouped["clusters"]:
        descs = [_description_of(texts, m) for m in members]
        shared = _shared_tokens(descs)
        name = _proposal_name("schema", members, shared, claimed_names)
        claimed_names.add(name)
        member_pairs = [
            by_pair[k]
            for k in (frozenset((a, b)) for i, a in enumerate(members) for b in members[i + 1:])
            if k in by_pair
        ]
        cofire = max((p.get("cofire") or 0.0) for p in member_pairs) if member_pairs else 0.0
        queries = []
        for p in sorted(member_pairs, key=lambda p: -(p.get("cofire") or 0.0)):
            q = (p.get("query") or "").strip()
            if q and q not in queries:
                queries.append(q)
            if len(queries) >= _MAX_QUERIES_SHOWN:
                break
        cited = sorted({c for m in members for c in _cited_paths_of(texts, m)})[:_MAX_CITED_PATHS]
        child_list = ", ".join(members[:_DESC_CHILD_LIST_LIMIT]) + (
            f" (+{len(members) - _DESC_CHILD_LIST_LIMIT} more)" if len(members) > _DESC_CHILD_LIST_LIMIT else ""
        )
        description = _truncate(
            f"Dream-drafted schema (UNCONFIRMED) — the shared pattern across {len(members)} "
            f"co-firing memories: {' '.join(shared) or 'see children'} ({child_list})",
            200,
        )
        body_lines = [_QUARANTINE_BANNER]
        body_lines.append(
            f"The following memories co-fire as one cluster (mutual co-fire, θ≥{th:g}):\n"
        )
        for m, d in zip(members, descs):
            body_lines.append(f"- [[{m}]] — {_truncate(d, 110) or 'no description'}")
        if shared:
            body_lines.append(f"\nShared vocabulary: {', '.join(shared)}.")
        if cited:
            body_lines.append("Evidence paths: " + ", ".join(cited))
        if queries:
            body_lines.append("Firing queries: " + " · ".join(f'"{_truncate(q, 60)}"' for q in queries))
        proposals["schemas"].append(
            {
                "kind": "schema",
                "name": name,
                "description": description,
                "body": "\n".join(body_lines) + "\n",
                "children": list(members),
                "cofire": round(cofire, 4),
                "queries": queries,
                "cited_paths": cited,
            }
        )

    for p in grouped["hypothesis_pairs"]:
        a, b = p["a"], p["b"]
        descs = [_description_of(texts, a), _description_of(texts, b)]
        shared = _shared_tokens(descs)
        name = _proposal_name("hypothesis", [a, b], shared, claimed_names)
        claimed_names.add(name)
        cited = sorted(set(_cited_paths_of(texts, a)) | set(_cited_paths_of(texts, b)))[:_MAX_CITED_PATHS]
        description = _truncate(
            f"Dream-drafted hypothesis (UNCONFIRMED): {a} and {b} co-fire strongly "
            f"(cofire={p.get('cofire'):.2f}) from disconnected graph regions — likely a "
            f"latent connection via {' '.join(shared) or 'shared context'}",
            200,
        )
        q = (p.get("query") or "").strip()
        body_lines = [_QUARANTINE_BANNER]
        body_lines.append(
            f"[[{a}]] and [[{b}]] co-fire mutually at {p.get('cofire'):.2f} yet share no "
            f"graph path (distance unknown/disconnected):\n"
        )
        body_lines.append(f"- [[{a}]] — {_truncate(descs[0], 110) or 'no description'}")
        body_lines.append(f"- [[{b}]] — {_truncate(descs[1], 110) or 'no description'}")
        if shared:
            body_lines.append(f"\nShared vocabulary: {', '.join(shared)}.")
        if cited:
            body_lines.append("Evidence paths: " + ", ".join(cited))
        if q:
            body_lines.append(f'Firing query: "{_truncate(q, 60)}"')
        body_lines.append(
            "\nIf real work confirms the connection, link or merge the two memories "
            "(this hypothesis then graduates on its recorded outcome, or is superseded "
            "by the explicit edge)."
        )
        proposals["hypotheses"].append(
            {
                "kind": "hypothesis",
                "name": name,
                "description": description,
                "body": "\n".join(body_lines) + "\n",
                "children": [a, b],
                "cofire": round(p.get("cofire") or 0.0, 4),
                "queries": [q] if q else [],
                "cited_paths": cited,
            }
        )
    return proposals


# --------------------------------------------------------------------------- #
# Staging (the Tier-B write path — capped, blocked, stamped, ledgered, undoable)
# --------------------------------------------------------------------------- #
def _stamp_line(edge_id: str, pass_id: str, kind: str, cofire: float) -> str:
    return f"<!-- dream: generated {kind} · pass={pass_id} · edge={edge_id} · cofire={cofire:.2f} -->"


def proposals_ledger_path(telemetry_dir: str, pass_id: str) -> str:
    return os.path.join(dream_dir(telemetry_dir), f"proposals-{pass_id}.jsonl")


def write_proposals_ledger(telemetry_dir: str, pass_id: str, proposals: dict) -> Optional[str]:
    """Persist the pass's proposals (staged or not) under the DERIVED dream dir (inv1).
    Written only when there is at least one proposal. Never raises."""
    rows = (proposals.get("schemas") or []) + (proposals.get("hypotheses") or [])
    if not rows:
        return None
    try:
        os.makedirs(dream_dir(telemetry_dir), exist_ok=True)
        path = proposals_ledger_path(telemetry_dir, pass_id)
        stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
        with open(path, "w", encoding="utf-8") as fh:
            for row in rows:
                fh.write(json.dumps({"pass": pass_id, **row, "generated_at": stamp}, ensure_ascii=False) + "\n")
        return path
    except Exception:
        return None


def _prior_decided_children(memory_dir: str) -> Dict[frozenset, str]:
    """Children-sets with a STANDING VERDICT — undone, archived, or expired — plus live
    ones (active/graduated). The ping-pong guard: a cluster the owner (or the horizon)
    already rejected is never auto re-staged; a cluster already staged is not duplicated."""
    out: Dict[frozenset, str] = {}
    for row in generated_rows(memory_dir):
        children = row.get("children")
        if not isinstance(children, list) or not children:
            continue
        key = frozenset(str(c) for c in children)
        state = row.get("state")
        if state in ("undone", "archived"):
            out[key] = str(state)
        elif state == "active":
            if row.get("expired"):
                out[key] = "expired"
            elif row.get("confidence") == "verified":
                out[key] = "graduated"
            else:
                out[key] = "staged"
    return out


def stage_generated(
    memory_dir: str,
    proposals: dict,
    *,
    pass_id: str,
    telemetry_dir: Optional[str] = None,
    index_dir: Optional[str] = None,
    repo_root: Optional[str] = None,
) -> dict:
    """Stage proposals into the corpus as ``confidence: draft`` memories. Capped, hard
    secret-BLOCKed, stamped, ledgered, trust-folded, undoable. Returns
    ``{"staged": [ledger rows], "refused": [(proposal, reason)]}``. Never raises.

    Every staged memory is created through ``new_memory.write_memory`` (the ONE canonical
    create primitive: refuses overwrite, folds SEC-6 authorship-consent, refreshes the
    index) with the confidence argument HARD-CODED to ``"draft"`` — the created-only-at-
    draft acceptance criterion lives here, not in the proposal data.
    """
    from .dream import read_apply_ledger
    from .new_memory import write_memory
    from .secrets import scan_text
    from .trust import file_sha256

    td = telemetry_dir or default_telemetry_dir(memory_dir)
    out: dict = {"staged": [], "refused": []}
    ordered = (proposals.get("schemas") or []) + (proposals.get("hypotheses") or [])
    if not ordered:
        return out
    cap = max_generate_per_pass()
    soak = soak_status(td, memory_dir=memory_dir)
    distinct_now = int(soak.get("distinct_sessions") or 0)
    session_id = current_session_id(td)
    now_iso = datetime.now(timezone.utc).isoformat(timespec="seconds")
    prior = _prior_decided_children(memory_dir)
    # Edge-id continuation: pass ids have 1-second resolution, so two stagings inside
    # one second share a pass_id — the -gN counter continues past every id the ledger
    # already carries (an id collision would MERGE rows in read_apply_ledger).
    taken = {r.get("edge_id") for r in read_apply_ledger(memory_dir)}

    def _next_edge_id(n_staged: int) -> str:
        n = n_staged + 1
        while f"{pass_id}-g{n}" in taken:
            n += 1
        return f"{pass_id}-g{n}"

    ledger_rows: List[dict] = []
    staged_paths: List[str] = []
    for prop in ordered:
        if len(ledger_rows) >= cap:
            break
        kind = prop.get("kind")
        name = prop.get("name") or ""
        children = [str(c) for c in (prop.get("children") or [])]
        if kind not in _GENERATED_KINDS or not name or len(children) < 2:
            out["refused"].append((prop, "malformed proposal (kind/name/children)"))
            continue
        verdict = prior.get(frozenset(children))
        if verdict in ("undone", "archived", "expired"):
            out["refused"].append(
                (prop, f"this cluster was {verdict} before — never auto re-staged "
                       "(stage by hand if genuinely wanted)")
            )
            continue
        if verdict in ("staged", "graduated"):
            out["refused"].append((prop, f"a generated memory over this cluster is already {verdict}"))
            continue

        edge_id = _next_edge_id(len(ledger_rows))
        cofire = float(prop.get("cofire") or 0.0)
        body = (prop.get("body") or "").rstrip("\n") + "\n\n" + _stamp_line(edge_id, pass_id, kind, cofire) + "\n"
        ledger_row = {
            "edge_id": edge_id,
            "pass": pass_id,
            "kind": kind,
            "memory": name,
            "file": f"{name}.md",
            "children": children,
            "derives_from": children,
            "cofire": cofire,
            "confidence": "draft",
            "firing_query": (prop.get("queries") or [""])[0],
            "applied_at_session": session_id,
            "applied_at_distinct_count": distinct_now,
            "applied_at_ts": now_iso,
            "state": "active",
        }
        # Provenance completeness is a hard precondition (the DRM-2 discipline).
        if not all(ledger_row.get(k) not in (None, "") for k in ("edge_id", "pass", "kind", "memory")):
            out["refused"].append((prop, "incomplete provenance"))
            continue
        # HARD secret BLOCK over every generated byte — file content AND ledger row
        # (the ratified dream-write-path deviation: REFUSED, not warned).
        rationale = "\n".join(
            [name, prop.get("description") or "", body, json.dumps(ledger_row, ensure_ascii=False)]
        )
        findings = scan_text(rationale)
        if findings:
            out["refused"].append((prop, f"secret lint BLOCK: {'; '.join(findings)}"))
            continue

        res = write_memory(
            name,
            prop.get("description") or "",
            "project",  # never floor material (only user/feedback reach MEMORY.md)
            body=body,
            memory_dir=memory_dir,
            repo_root=repo_root,
            confidence="draft",  # HARD-CODED: created ONLY at draft (DREAM-KILL-1)
            origin=f"dream:{pass_id}",
            no_links=True,  # the body's [[children]] ARE the links; no GRA-3 discovery
        )
        if not res.get("created") or not res.get("path"):
            out["refused"].append((prop, f"write_memory refused: {res.get('error') or 'unknown'}"))
            continue
        path = res["path"]
        staged_paths.append(path)

        # Typed derivation provenance: the parent declares its children (derives-from,
        # the DRM-6 relation). Additive, idempotent, per-item — links.add_typed_relation
        # folds each write into the SEC-6 consent baseline itself.
        from .links import add_typed_relation

        for child in children:
            add_typed_relation(path, "derives-from", child)

        # cited_paths: the union of the children's cited files is the draft's OUTCOME
        # surface (injection_hits joins on it — no cited paths, no graduation evidence).
        # write_memory's own backfill derives body-named paths that EXIST in the repo;
        # when it found some, its validated list wins. Missing or empty (non-git /
        # hermetic corpora, or evidence paths outside this repo), set the union
        # explicitly — a draft with no outcome surface could never graduate.
        try:
            cited = [str(c) for c in (prop.get("cited_paths") or [])]
            if cited:
                with open(path, "r", encoding="utf-8") as fh:
                    text = fh.read()
                fm_now = parse_frontmatter(text) or {}
                meta_now = fm_now.get("metadata") if isinstance(fm_now.get("metadata"), dict) else {}
                existing_cited = fm_now.get("cited_paths")
                if existing_cited is None:
                    existing_cited = (meta_now or {}).get("cited_paths")
                if not existing_cited:
                    _set_cited_paths(path, cited)
        except Exception:
            pass

        # Fold the FINAL bytes (post typed-edges, post cited-paths) into the consent
        # baseline, and record that hash as the undo oracle: undo deletes the file only
        # if it is byte-identical to what staging left — a hand-edited or graduated
        # draft refuses (protect the human's/evidence's work; use git from there).
        try:
            from .trust import record_authored_write

            record_authored_write(memory_dir, path, repo_root)
        except Exception:
            pass
        h = file_sha256(path)
        ledger_row["undo"] = {"file": f"{name}.md", "created": True, "sha256": h}
        ledger_rows.append(ledger_row)
        out["staged"].append(ledger_row)

    if ledger_rows:
        try:
            with open(apply_ledger_path(memory_dir), "a", encoding="utf-8") as fh:
                for row in ledger_rows:
                    fh.write(json.dumps(row, ensure_ascii=False) + "\n")
        except Exception as exc:
            # A ledger append failure would orphan stamps — roll the staging back.
            for p in staged_paths:
                try:
                    os.remove(p)
                except Exception:
                    pass
            out["staged"] = []
            out["refused"].append(({"name": "(pass)"}, f"ledger append FAILED ({exc}) — staging rolled back"))
            return out
        _refresh_index_quiet(memory_dir, index_dir)
    return out


def _refresh_index_quiet(memory_dir: str, index_dir: Optional[str]) -> None:
    try:
        from .build_index import default_index_dir, refresh_index

        refresh_index(memory_dir, index_dir or default_index_dir(memory_dir))
    except Exception:
        pass


# --------------------------------------------------------------------------- #
# The decay sweep — graduation (external evidence ONLY) + horizon expiry
# --------------------------------------------------------------------------- #
def _set_confidence(path: str, value: str, *, dry_run: bool = False) -> dict:
    """Rewrite ONE memory's ``confidence:`` frontmatter value (body byte-identical).

    The graduation primitive. Mirrors ``staleness.set_invalid_after``'s frontmatter
    discipline: metadata-nesting aware, refuses on missing/unparseable frontmatter,
    idempotent on the same value, never raises. Deliberately per-item, no batch.
    """
    result = {"path": path, "changed": False, "confidence": value, "error": None}
    try:
        with open(path, "r", encoding="utf-8") as fh:
            text = fh.read()
        if not text.startswith("---"):
            result["error"] = "no frontmatter"
            return result
        fm = parse_frontmatter(text)
        if not fm:
            result["error"] = "unparseable frontmatter -- refusing to write (fix the YAML)"
            return result
        lines = text.split("\n")
        close = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
        if close is None:
            result["error"] = "no frontmatter"
            return result
        key_re = re.compile(r"^(\s*)confidence\s*:")
        idx = next((i for i in range(1, close) if key_re.match(lines[i])), None)
        if idx is None:
            # Insert via the ONE shared walk (COR-9/COR-14) — nested under metadata:
            # when present, at that block's OWN child indent. This writer used to
            # hard-code two spaces, so a hand-reformatted draft (4-space children)
            # became a document that no longer parses.
            from .provenance import insert_frontmatter_keys

            lines[1:close] = insert_frontmatter_keys(
                lines[1:close], [f"confidence: {value}"]
            )
        else:
            indent = key_re.match(lines[idx]).group(1)
            new_line = f"{indent}confidence: {value}"
            if lines[idx] == new_line:
                return result  # idempotent
            lines[idx] = new_line
        new_text = "\n".join(lines)
        # COR-14: the write-site damage check every frontmatter writer answers — did
        # this rewrite touch any key it does not own, or stop the document parsing?
        from .provenance import _frontmatter_damage

        damage = _frontmatter_damage(text, new_text, {"confidence"})
        if damage:
            result["error"] = (
                f"refusing to rewrite {os.path.basename(path)}: {damage} — "
                "this is a hippo bug, please report it"
            )
            return result
        result["changed"] = new_text != text
        if result["changed"] and not dry_run:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new_text)
            try:
                from .trust import record_authored_write

                record_authored_write(os.path.dirname(path), path)
            except Exception:
                pass
    except Exception as exc:
        result["error"] = str(exc)
    return result


def _set_cited_paths(path: str, paths: List[str], *, dry_run: bool = False) -> dict:
    """Set ONE memory's ``cited_paths`` frontmatter to ``paths`` (body byte-identical).

    Staging-time only, and only when the canonical backfill left the key missing/empty —
    the draft's outcome surface must exist for graduation evidence to ever accrue. Same
    frontmatter discipline as ``_set_confidence``; drops block-style continuation lines
    exactly like ``links.add_typed_relation`` (values re-rendered as one flow list).
    """
    result = {"path": path, "changed": False, "error": None}
    try:
        with open(path, "r", encoding="utf-8") as fh:
            text = fh.read()
        if not text.startswith("---"):
            result["error"] = "no frontmatter"
            return result
        if not parse_frontmatter(text):
            result["error"] = "unparseable frontmatter -- refusing to write (fix the YAML)"
            return result
        lines = text.split("\n")
        close = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
        if close is None:
            result["error"] = "no frontmatter"
            return result
        value = "[" + ", ".join(json.dumps(p) for p in paths) + "]"
        key_re = re.compile(r"^(\s*)cited_paths\s*:")
        idx = next((i for i in range(1, close) if key_re.match(lines[i])), None)
        if idx is None:
            # COR-14: same shared insert walk as _set_confidence — indent read from
            # the metadata block's own keys, never hard-coded.
            from .provenance import insert_frontmatter_keys

            lines[1:close] = insert_frontmatter_keys(
                lines[1:close], [f"cited_paths: {value}"]
            )
        else:
            indent = key_re.match(lines[idx]).group(1)
            end = idx + 1
            while end < close and re.match(r"^\s+-\s", lines[end]):
                end += 1
            lines[idx:end] = [f"{indent}cited_paths: {value}"]
        new_text = "\n".join(lines)
        from .provenance import _frontmatter_damage

        damage = _frontmatter_damage(text, new_text, {"cited_paths"})
        if damage:
            result["error"] = (
                f"refusing to rewrite {os.path.basename(path)}: {damage} — "
                "this is a hippo bug, please report it"
            )
            return result
        result["changed"] = new_text != text
        if result["changed"] and not dry_run:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(new_text)
    except Exception as exc:
        result["error"] = str(exc)
    return result


def _live_confidence(memory_dir: str, stem: str) -> Optional[str]:
    try:
        from .build_index import _extract_confidence

        with open(os.path.join(memory_dir, f"{stem}.md"), "r", encoding="utf-8") as fh:
            return _extract_confidence(parse_frontmatter(fh.read()))
    except Exception:
        return None


def draft_sweep_state(
    memory_dir: str, telemetry_dir: Optional[str] = None
) -> dict:
    """The sweep's PURE half: what would graduate, what has expired, and the alarm.

    Graduation is gated on EXTERNAL evidence only — ``outcome.injection_hits`` (the
    recorded-outcome join). There is deliberately NO other path to ``verified`` for a
    generated draft: not a pass re-reading its own output, not a human glance — evidence
    or the horizon. Read-only; never raises.
    """
    from .outcome import injection_hits

    td = telemetry_dir or default_telemetry_dir(memory_dir)
    out = {"rows": [], "graduate": [], "expire": [], "awaiting_archive": [], "alarm": {}}
    try:
        rows = generated_rows(memory_dir)
        if not rows:
            out["alarm"] = _alarm_stats(rows)
            return out
        distinct_now = int(soak_status(td, memory_dir=memory_dir).get("distinct_sessions") or 0)
        hits = injection_hits(memory_dir, td)
        horizon = draft_horizon()
        for row in rows:
            stem = row.get("memory")
            if row.get("state") != "active" or not isinstance(stem, str):
                continue
            live_conf = _live_confidence(memory_dir, stem)
            info = {
                "row": row,
                "stem": stem,
                "confidence": live_conf,
                "age": distinct_now - int(row.get("applied_at_distinct_count") or 0),
            }
            out["rows"].append(info)
            if live_conf != "draft":
                continue  # graduated already (or hand-regraded) — the horizon no longer applies
            ev = hits.get(stem)
            if ev and int(ev.get("hits") or 0) >= 1:
                out["graduate"].append({**info, "evidence": ev})
            elif row.get("expired"):
                out["awaiting_archive"].append(info)
            elif info["age"] >= horizon:
                out["expire"].append(info)
        out["alarm"] = _alarm_stats(rows)
        return out
    except Exception:
        return out


def _alarm_stats(rows: List[dict]) -> dict:
    """The graduation-rate / draft-reject hallucination alarm — proposal signal-to-noise.

    ``decided`` = drafts the world has ruled on (graduated / expired / archived /
    undone). A LOW graduation share among the decided means the generator asserts claims
    reality never confirms — the alarm names it loudly instead of letting quiet decay
    read as health."""
    staged = len(rows)
    graduated = sum(1 for r in rows if r.get("state") == "active" and r.get("confidence") == "verified")
    archived = sum(1 for r in rows if r.get("state") == "archived")
    undone = sum(1 for r in rows if r.get("state") == "undone")
    expired_pending = sum(
        1 for r in rows if r.get("state") == "active" and r.get("expired") and r.get("confidence") != "verified"
    )
    pending = sum(
        1
        for r in rows
        if r.get("state") == "active" and not r.get("expired") and r.get("confidence") != "verified"
    )
    decided = graduated + archived + undone + expired_pending
    rate = (graduated / decided) if decided else None
    return {
        "staged": staged,
        "graduated": graduated,
        "expired_pending_archive": expired_pending,
        "archived": archived,
        "undone": undone,
        "pending": pending,
        "decided": decided,
        "graduation_rate": (round(rate, 3) if rate is not None else None),
        "alarm": bool(decided >= _ALARM_MIN_DECIDED and rate is not None and rate < _ALARM_GRADUATION_FLOOR),
    }


def sweep_drafts(
    memory_dir: str,
    telemetry_dir: Optional[str] = None,
    index_dir: Optional[str] = None,
    *,
    repo_root: Optional[str] = None,
) -> Tuple[int, str]:
    """Execute the decay sweep: graduate evidence-confirmed drafts, expire horizon-old
    ones (auto-close their validity window — /dream's own artifact, reversible), and
    PROPOSE archives (per-item execution stays with ``--archive-draft``, inv4).

    Runs inside every apply pass whenever generated rows exist — the tier's self-decay
    never depends on the flag staying on — and stands alone as ``dream --sweep-drafts``.
    """
    from .staleness import set_invalid_after

    td = telemetry_dir or default_telemetry_dir(memory_dir)
    state = draft_sweep_state(memory_dir, td)
    alarm = state.get("alarm") or {}
    if not state["rows"] and not alarm.get("staged"):
        return 0, "🌱 dream drafts: none staged — nothing to sweep."

    now_iso = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines: List[str] = []
    ledger_appends: List[dict] = []
    wrote = False

    for item in state["graduate"]:
        stem, row, ev = item["stem"], item["row"], item["evidence"]
        res = _set_confidence(os.path.join(memory_dir, f"{stem}.md"), "verified")
        if res.get("error"):
            lines.append(f"  ✘ graduation of {stem} failed: {res['error']}")
            continue
        wrote = wrote or res.get("changed", False)
        ledger_appends.append(
            {
                "edge_id": row.get("edge_id"),
                "pass": row.get("pass"),
                "state": "active",
                "confidence": "verified",
                "graduated_at_ts": now_iso,
                "evidence": {"hits": ev.get("hits"), "sessions": ev.get("sessions")},
            }
        )
        lines.append(
            f"  ✓ GRADUATED {stem} draft→verified — recorded outcome evidence "
            f"({ev.get('hits')} hit session(s): {', '.join(ev.get('sessions') or [])}). "
            f"Still firewalled from /dream's own source set until it ages in."
        )

    for item in state["expire"]:
        stem, row = item["stem"], item["row"]
        res = set_invalid_after(os.path.join(memory_dir, f"{stem}.md"))
        if res.get("error"):
            lines.append(f"  ✘ expiry of {stem} failed: {res['error']}")
            continue
        wrote = True
        ledger_appends.append(
            {
                "edge_id": row.get("edge_id"),
                "pass": row.get("pass"),
                "state": "active",
                "expired": True,
                "expired_at_ts": now_iso,
            }
        )
        lines.append(
            f"  ⌛ EXPIRED {stem} — unconfirmed for {item['age']} distinct sessions "
            f"(horizon {draft_horizon()}): validity window closed (recall demotes it "
            f"further); ARCHIVE PROPOSED — execute with "
            f"`python -m memory.dream --archive-draft {stem}`."
        )

    for item in state["awaiting_archive"]:
        lines.append(
            f"  ⌛ {item['stem']} expired earlier and still awaits its per-item archive "
            f"(`--archive-draft {item['stem']}`)."
        )

    if ledger_appends:
        try:
            with open(apply_ledger_path(memory_dir), "a", encoding="utf-8") as fh:
                for row in ledger_appends:
                    fh.write(json.dumps(row, ensure_ascii=False) + "\n")
        except Exception as exc:
            return 1, f"🌱 dream drafts: sweep ledger append FAILED ({exc}) — re-run the sweep."
    if wrote:
        _refresh_index_quiet(memory_dir, index_dir)

    alarm = draft_sweep_state(memory_dir, td).get("alarm") or {}
    head = (
        f"🌱 dream drafts (generative tier): {alarm.get('staged', 0)} staged ever — "
        f"{alarm.get('pending', 0)} pending · {alarm.get('graduated', 0)} graduated · "
        f"{alarm.get('expired_pending_archive', 0)} expired-awaiting-archive · "
        f"{alarm.get('archived', 0)} archived · {alarm.get('undone', 0)} undone"
    )
    rate = alarm.get("graduation_rate")
    if rate is not None:
        head += f" · graduation_rate={rate}"
    lines.insert(0, head)
    if alarm.get("alarm"):
        lines.append(
            f"  🚨 HALLUCINATION ALARM: only {rate} of decided drafts earned outcome "
            f"evidence (floor {_ALARM_GRADUATION_FLOOR:.2f}) — the generator is asserting "
            "claims real work never confirms. Keep HIPPO_DREAM_GENERATIVE off, or raise "
            "θ / DREAM_SCHEMA_MIN_CLUSTER before staging more."
        )
    if not state["graduate"] and not state["expire"] and not state["awaiting_archive"]:
        lines.append("  nothing to graduate or expire this pass (evidence and horizon both quiet).")
    return 0, "\n".join(lines)


def archive_draft(
    memory_dir: str,
    name: str,
    *,
    repo_root: Optional[str] = None,
    telemetry_dir: Optional[str] = None,
    index_dir: Optional[str] = None,
) -> dict:
    """Execute ONE proposed draft archive (per-item, inv4). Refuses when ``name`` is not
    an ACTIVE dream-generated memory — non-generated memories use the normal audit
    archive flow, never this shortcut. Never raises."""
    from .archive import archive_memory

    result = {"name": name, "archived": False, "error": None}
    row = next(
        (r for r in generated_rows(memory_dir) if r.get("memory") == name and r.get("state") == "active"),
        None,
    )
    if row is None:
        result["error"] = (
            "not an ACTIVE dream-generated memory (see dream --log); for human memories "
            "use the audit archive flow"
        )
        return result
    rr = repo_root or os.path.dirname(os.path.dirname(os.path.abspath(memory_dir)))
    res = archive_memory(name, memory_dir, rr)
    if not res.get("moved"):
        result["error"] = res.get("error") or (
            f"refused — inbound referrers: {', '.join(res.get('referrers') or [])}"
        )
        return result
    try:
        with open(apply_ledger_path(memory_dir), "a", encoding="utf-8") as fh:
            fh.write(
                json.dumps(
                    {
                        "edge_id": row.get("edge_id"),
                        "pass": row.get("pass"),
                        "state": "archived",
                        "archived_at_ts": datetime.now(timezone.utc).isoformat(timespec="seconds"),
                    },
                    ensure_ascii=False,
                )
                + "\n"
            )
    except Exception as exc:
        result["error"] = f"archived on disk but the ledger append failed: {exc}"
        return result
    _refresh_index_quiet(memory_dir, index_dir)
    result["archived"] = True
    return result


# --------------------------------------------------------------------------- #
# Prospective recall — freeze the abstention backlog, count abstain→hit flips
# --------------------------------------------------------------------------- #
def frozen_backlog_path(telemetry_dir: str) -> str:
    return os.path.join(dream_dir(telemetry_dir), _FROZEN_BACKLOG_NAME)


def freeze_abstention_backlog(telemetry_dir: str) -> dict:
    """Freeze the CURRENT abstention backlog under the derived dream dir (inv1) — once.

    An existing frozen file is kept (frozen means frozen: the baseline predates the
    staged drafts, which is exactly what makes a later flip attributable). Returns the
    frozen payload. Never raises; ``{"clusters": []}`` on failure."""
    from .telemetry import abstention_backlog

    try:
        path = frozen_backlog_path(telemetry_dir)
        if os.path.isfile(path):
            with open(path, "r", encoding="utf-8") as fh:
                payload = json.load(fh)
            if isinstance(payload, dict) and isinstance(payload.get("clusters"), list):
                return payload
        clusters = abstention_backlog(telemetry_dir)
        payload = {
            "frozen_at_ts": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "clusters": [
                {
                    "sample_query": c.get("sample_query"),
                    "count": c.get("count"),
                    "terms": list(c.get("terms") or []),
                }
                for c in clusters
            ],
        }
        os.makedirs(dream_dir(telemetry_dir), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, ensure_ascii=False, indent=1)
        return payload
    except Exception:
        return {"clusters": []}


def prospective_recall(
    memory_dir: str,
    telemetry_dir: Optional[str] = None,
    index_dir: Optional[str] = None,
    *,
    k: int = 10,
) -> dict:
    """The DRM-6 metric: over the FROZEN backlog, which recorded abstentions now HIT —
    and which flips surface a dream-generated memory (attribution).

    Offline, measure-only (inv6): the same supplied-index + index_dir call shape the
    eval metrics use (graph expansion + the DRM-6 quarantine guard both active), never
    the hot path, never a write. ``{"frozen_at_ts", "clusters", "flips",
    "flips_via_dream", "per_query": [...]}``; a missing frozen baseline reports itself.
    """
    from .build_index import default_index_dir, load_index
    from .recall import recall

    td = telemetry_dir or default_telemetry_dir(memory_dir)
    out = {"frozen_at_ts": None, "clusters": 0, "flips": 0, "flips_via_dream": 0, "per_query": []}
    try:
        path = frozen_backlog_path(td)
        if not os.path.isfile(path):
            out["note"] = (
                "no frozen abstention baseline yet — it freezes automatically at first "
                "staging, or freeze explicitly via dream --generate"
            )
            return out
        with open(path, "r", encoding="utf-8") as fh:
            payload = json.load(fh)
        clusters = payload.get("clusters") or []
        out["frozen_at_ts"] = payload.get("frozen_at_ts")
        out["clusters"] = len(clusters)
        idx_dir = index_dir or default_index_dir(memory_dir)
        idx = load_index(idx_dir)
        if idx is None or not len(idx):
            out["note"] = "no recall index — build one first (nothing measured)"
            return out
        known = {e.get("name") for e in idx.entries}
        dream_stems = {
            r.get("memory") for r in generated_rows(memory_dir) if r.get("state") == "active"
        }
        for c in clusters:
            q = (c.get("sample_query") or "").strip()
            if not q:
                continue
            res = recall(q, k=k, index=idx, index_dir=idx_dir)
            names = [r.get("name") for r in res if r.get("name") in known]
            hit = bool(names)
            via_dream = bool(set(names) & dream_stems)
            out["flips"] += 1 if hit else 0
            out["flips_via_dream"] += 1 if via_dream else 0
            out["per_query"].append(
                {
                    "query": q,
                    "count": c.get("count"),
                    "hit": hit,
                    "via_dream": via_dream,
                    "hits": names[:5],
                }
            )
        return out
    except Exception:
        return out


def render_prospective(metric: dict) -> str:
    lines = [
        f"🔭 prospective recall — frozen abstention backlog "
        f"({metric.get('clusters', 0)} cluster(s), frozen {metric.get('frozen_at_ts') or 'never'}): "
        f"{metric.get('flips', 0)} abstain→hit flip(s), {metric.get('flips_via_dream', 0)} "
        f"surfacing a dream-generated memory"
    ]
    if metric.get("note"):
        lines.append(f"   {metric['note']}")
    for row in metric.get("per_query") or []:
        mark = "✓" if row.get("hit") else "·"
        via = " ★via-dream" if row.get("via_dream") else ""
        lines.append(
            f"   {mark} \"{row.get('query', '')[:60]}\" (asked {row.get('count')}×)"
            + (f" → {', '.join(row.get('hits') or [])}" if row.get("hit") else " → still abstains")
            + via
        )
    if not metric.get("per_query"):
        lines.append("   (empty backlog — no recurring abstentions were recorded before staging)")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Pass orchestration (called from memory.dream's CLI / apply pass / MCP)
# --------------------------------------------------------------------------- #
def run_generative_pass(
    memory_dir: str,
    index_dir: Optional[str] = None,
    telemetry_dir: Optional[str] = None,
    *,
    stage: bool = False,
    probe_k: Optional[int] = None,
    max_seeds: Optional[int] = None,
    repo_root: Optional[str] = None,
    result: Optional[dict] = None,
) -> Tuple[int, str]:
    """Discover → cluster → propose → (optionally) stage, with the decay sweep first.

    ``stage=False`` is REPORT-ONLY end to end: proposals print + land under the derived
    dream dir, zero memory writes, no sweep (a report pass must not write). ``stage=True``
    re-checks the SEC-1 trust gate, runs the decay sweep (graduate/expire), then stages
    up to the cap. ``result`` lets the apply pass hand over its own discovery result so
    the corpus is probed once per pass, not twice.
    """
    from .dream import discover

    td = telemetry_dir or default_telemetry_dir(memory_dir)
    lines: List[str] = []

    if stage:
        from . import trust

        gate_root = trust.gate_repo_root(memory_dir, repo_root)
        if gate_root is not None and not trust.is_trusted(gate_root):
            return 1, (
                "🌱 dream --generate: STAGING REFUSED — this corpus is untrusted (SEC-1). "
                "The report-only form (no --stage) remains available."
            )
        if generated_rows(memory_dir):
            _sc, sweep_text = sweep_drafts(memory_dir, td, index_dir, repo_root=repo_root)
            lines.append(sweep_text)

    if result is None:
        result = discover(memory_dir, index_dir, td, probe_k=probe_k, max_seeds=max_seeds)
    if result.get("status") != "ok":
        lines.append(
            f"🌱 dream --generate {result.get('pass_id', '?')} — no proposals: {result.get('reason')}"
        )
        return (1 if result.get("status") == "no-index" else 0), "\n".join(lines)

    texts: Dict[str, str] = {}
    try:
        from .dream import _corpus_texts

        texts = _corpus_texts(memory_dir)
    except Exception:
        pass
    proposals = propose_generative(result, texts)
    pass_id = result.get("pass_id", "?")
    ledger_path = write_proposals_ledger(td, pass_id, proposals)
    n_s, n_h = len(proposals["schemas"]), len(proposals["hypotheses"])

    lines.append(
        f"🌱 dream generative pass {pass_id} — {n_s} schema / {n_h} hypothesis proposal(s) "
        f"(flag {'ON' if generative_enabled() else 'OFF'}; mode: {'STAGE' if stage else 'report-only'})"
    )
    if ledger_path:
        lines.append(f"   proposals ledger: {ledger_path}")
    if n_s == n_h == 0:
        lines.append(
            "   empty — no mutual co-firing cluster (≥"
            f"{schema_min_cluster()}) or distant pair above θ this pass (the norm)."
        )
    for p in proposals["schemas"] + proposals["hypotheses"]:
        lines.append(
            f"   • {p['kind']:<10} {p['name']}  cofire={p['cofire']:.2f}  "
            f"children: {', '.join(p['children'])}"
        )
    for big in proposals.get("oversized") or []:
        lines.append(
            f"   ⚠ oversized cluster SKIPPED ({len(big)} members > "
            f"{schema_max_cluster()}): {', '.join(big[:6])}… — θ under-discriminates at "
            "this density; a schema over it would be a haystack (and born over DRM-4's "
            "hub bar). Raise DREAM_COFIRE_THETA before staging."
        )

    if stage and (n_s or n_h):
        freeze_abstention_backlog(td)  # the prospective baseline predates the staging
        staged = stage_generated(
            memory_dir,
            proposals,
            pass_id=pass_id,
            telemetry_dir=td,
            index_dir=index_dir,
            repo_root=repo_root,
        )
        for row in staged["staged"]:
            lines.append(
                f"   ✚ STAGED {row['memory']} ({row['kind']}, confidence: draft, "
                f"[{row['edge_id']}]) — down-weighted in recall, expires at horizon "
                f"{draft_horizon()} unless outcome evidence graduates it; undo with "
                f"`python -m memory.dream --undo {row['edge_id']}`"
            )
        for prop, reason in staged["refused"]:
            lines.append(f"   ✘ refused {prop.get('name', '?')}: {reason}")
        if not staged["staged"]:
            lines.append("   staged 0 (cap/guards) — see refusals above." if staged["refused"] else "   staged 0.")
        lines.append(
            "   commit stays yours (never auto-committed); drafts never answer alone and "
            "are firewalled from /dream's own source set."
        )
    elif n_s or n_h:
        lines.append(
            "   report-only: stage with `dream --generate --stage` (explicit) or set "
            "HIPPO_DREAM_GENERATIVE=1 to let apply passes stage up to the cap."
        )
    return 0, "\n".join(lines)
